### ISSUE TITLE
deadinside.pas где кавычки в writeln

### ISSUE THREAD

**Issue by timofej673** [itsyuni/1000-7#7]
код не работает

**Comment by timofej673** [comment]
и в си плюс плюс пофиксил

**Comment by GeorgNation** [comment]
> и в си плюс плюс пофиксил

Зачем? У меня код работал. Последней версии.

**Comment by GeorgNation** [comment]
> > > и в си плюс плюс пофиксил
> > 
> > Зачем? У меня код работал. Последней версии.
> 
> я добавил там поддержку windows
> 

Так оно и до твоих исправлений на Windows работало. Я скомпилировал файл и добавил в релиз как бы. Все работает идеально. Так что, лучше сделать revert.

**Comment by GeorgNation** [comment]
> ![Ошибка при компиляции](https://user-images.githubusercontent.com/54764164/137326244-b491c9a2-b667-4c3f-a373-368570fe416a.png) Ну вот что мне пишет при компиляции

Потому-что надо MingW-w64 скачивать. Там есть G++.
